services:
  clearervoice:
    container_name: clearervoice-denoiser
    build:
      context: .
      dockerfile: Dockerfile
    #env_file: .env.dev
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD:/workdir
      - /mnt/d/MEGAN/data:/datasets
